package qingyun.ele.domain.db;
// Generated 2017-6-25 11:08:16 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerData generated by hbm2java
 */
@Entity
@Table(name="customer_data"
    ,catalog="ele"
)
public class CustomerData  implements java.io.Serializable {


     private Long id;
     private Long idCustomer;
     private String customerName;
     private String customerCode;
     private String timeDuration;
     private Float capacity;
     private String customerAddress;
     private String c1;
     private String c2;
     private String c3;
     private String c4;
     private String c5;
     private String c6;
     private String c7;
     private String c8;
     private String c9;
     private String c10;
     private String c11;
     private String c12;
     private String c13;
     private String c14;
     private String c15;
     private String c16;
     private String c17;
     private String c18;
     private String c19;
     private String c20;
     private String c21;
     private String c22;
     private String c23;
     private String inverterSn;
     private String channel;
     private Float temp;
     private Date CTime;
     private Float vpv1;
     private Float vpv2;
     private Float vpv3;
     private Float lpv1;
     private Float lpv2;
     private Float lpv3;
     private Float vac1;
     private Float vac2;
     private Float vac3;
     private Float lac1;
     private Float lac2;
     private Float lac3;
     private Float pac1;
     private Float pac2;
     private Float pac3;
     private Float fac;
     private Float todayEne;
     private Float totalEne;

    public CustomerData() {
    }

    public CustomerData(Long idCustomer, String customerName, String customerCode, String timeDuration, Float capacity, String customerAddress, String c1, String c2, String c3, String c4, String c5, String c6, String c7, String c8, String c9, String c10, String c11, String c12, String c13, String c14, String c15, String c16, String c17, String c18, String c19, String c20, String c21, String c22, String c23, String inverterSn, String channel, Float temp, Date CTime, Float vpv1, Float vpv2, Float vpv3, Float lpv1, Float lpv2, Float lpv3, Float vac1, Float vac2, Float vac3, Float lac1, Float lac2, Float lac3, Float pac1, Float pac2, Float pac3, Float fac, Float todayEne, Float totalEne) {
       this.idCustomer = idCustomer;
       this.customerName = customerName;
       this.customerCode = customerCode;
       this.timeDuration = timeDuration;
       this.capacity = capacity;
       this.customerAddress = customerAddress;
       this.c1 = c1;
       this.c2 = c2;
       this.c3 = c3;
       this.c4 = c4;
       this.c5 = c5;
       this.c6 = c6;
       this.c7 = c7;
       this.c8 = c8;
       this.c9 = c9;
       this.c10 = c10;
       this.c11 = c11;
       this.c12 = c12;
       this.c13 = c13;
       this.c14 = c14;
       this.c15 = c15;
       this.c16 = c16;
       this.c17 = c17;
       this.c18 = c18;
       this.c19 = c19;
       this.c20 = c20;
       this.c21 = c21;
       this.c22 = c22;
       this.c23 = c23;
       this.inverterSn = inverterSn;
       this.channel = channel;
       this.temp = temp;
       this.CTime = CTime;
       this.vpv1 = vpv1;
       this.vpv2 = vpv2;
       this.vpv3 = vpv3;
       this.lpv1 = lpv1;
       this.lpv2 = lpv2;
       this.lpv3 = lpv3;
       this.vac1 = vac1;
       this.vac2 = vac2;
       this.vac3 = vac3;
       this.lac1 = lac1;
       this.lac2 = lac2;
       this.lac3 = lac3;
       this.pac1 = pac1;
       this.pac2 = pac2;
       this.pac3 = pac3;
       this.fac = fac;
       this.todayEne = todayEne;
       this.totalEne = totalEne;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="id_customer")
    public Long getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(Long idCustomer) {
        this.idCustomer = idCustomer;
    }
    
    @Column(name="customer_name", length=64)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    
    @Column(name="customer_code", length=64)
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }
    
    @Column(name="time_duration", length=64)
    public String getTimeDuration() {
        return this.timeDuration;
    }
    
    public void setTimeDuration(String timeDuration) {
        this.timeDuration = timeDuration;
    }
    
    @Column(name="capacity", precision=12, scale=0)
    public Float getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Float capacity) {
        this.capacity = capacity;
    }
    
    @Column(name="customer_address", length=128)
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }
    
    @Column(name="c1", length=45)
    public String getC1() {
        return this.c1;
    }
    
    public void setC1(String c1) {
        this.c1 = c1;
    }
    
    @Column(name="c2", length=45)
    public String getC2() {
        return this.c2;
    }
    
    public void setC2(String c2) {
        this.c2 = c2;
    }
    
    @Column(name="c3", length=45)
    public String getC3() {
        return this.c3;
    }
    
    public void setC3(String c3) {
        this.c3 = c3;
    }
    
    @Column(name="c4", length=45)
    public String getC4() {
        return this.c4;
    }
    
    public void setC4(String c4) {
        this.c4 = c4;
    }
    
    @Column(name="c5", length=45)
    public String getC5() {
        return this.c5;
    }
    
    public void setC5(String c5) {
        this.c5 = c5;
    }
    
    @Column(name="c6", length=45)
    public String getC6() {
        return this.c6;
    }
    
    public void setC6(String c6) {
        this.c6 = c6;
    }
    
    @Column(name="c7", length=45)
    public String getC7() {
        return this.c7;
    }
    
    public void setC7(String c7) {
        this.c7 = c7;
    }
    
    @Column(name="c8", length=45)
    public String getC8() {
        return this.c8;
    }
    
    public void setC8(String c8) {
        this.c8 = c8;
    }
    
    @Column(name="c9", length=45)
    public String getC9() {
        return this.c9;
    }
    
    public void setC9(String c9) {
        this.c9 = c9;
    }
    
    @Column(name="c10", length=45)
    public String getC10() {
        return this.c10;
    }
    
    public void setC10(String c10) {
        this.c10 = c10;
    }
    
    @Column(name="c11", length=45)
    public String getC11() {
        return this.c11;
    }
    
    public void setC11(String c11) {
        this.c11 = c11;
    }
    
    @Column(name="c12", length=45)
    public String getC12() {
        return this.c12;
    }
    
    public void setC12(String c12) {
        this.c12 = c12;
    }
    
    @Column(name="c13", length=45)
    public String getC13() {
        return this.c13;
    }
    
    public void setC13(String c13) {
        this.c13 = c13;
    }
    
    @Column(name="c14", length=45)
    public String getC14() {
        return this.c14;
    }
    
    public void setC14(String c14) {
        this.c14 = c14;
    }
    
    @Column(name="c15", length=45)
    public String getC15() {
        return this.c15;
    }
    
    public void setC15(String c15) {
        this.c15 = c15;
    }
    
    @Column(name="c16", length=45)
    public String getC16() {
        return this.c16;
    }
    
    public void setC16(String c16) {
        this.c16 = c16;
    }
    
    @Column(name="c17", length=45)
    public String getC17() {
        return this.c17;
    }
    
    public void setC17(String c17) {
        this.c17 = c17;
    }
    
    @Column(name="c18", length=45)
    public String getC18() {
        return this.c18;
    }
    
    public void setC18(String c18) {
        this.c18 = c18;
    }
    
    @Column(name="c19", length=45)
    public String getC19() {
        return this.c19;
    }
    
    public void setC19(String c19) {
        this.c19 = c19;
    }
    
    @Column(name="c20", length=45)
    public String getC20() {
        return this.c20;
    }
    
    public void setC20(String c20) {
        this.c20 = c20;
    }
    
    @Column(name="c21", length=45)
    public String getC21() {
        return this.c21;
    }
    
    public void setC21(String c21) {
        this.c21 = c21;
    }
    
    @Column(name="c22", length=45)
    public String getC22() {
        return this.c22;
    }
    
    public void setC22(String c22) {
        this.c22 = c22;
    }
    
    @Column(name="c23", length=45)
    public String getC23() {
        return this.c23;
    }
    
    public void setC23(String c23) {
        this.c23 = c23;
    }
    
    @Column(name="inverter_sn", length=64)
    public String getInverterSn() {
        return this.inverterSn;
    }
    
    public void setInverterSn(String inverterSn) {
        this.inverterSn = inverterSn;
    }
    
    @Column(name="channel", length=64)
    public String getChannel() {
        return this.channel;
    }
    
    public void setChannel(String channel) {
        this.channel = channel;
    }
    
    @Column(name="temp", precision=12, scale=0)
    public Float getTemp() {
        return this.temp;
    }
    
    public void setTemp(Float temp) {
        this.temp = temp;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="c_time", length=19)
    public Date getCTime() {
        return this.CTime;
    }
    
    public void setCTime(Date CTime) {
        this.CTime = CTime;
    }
    
    @Column(name="vpv1", precision=12, scale=0)
    public Float getVpv1() {
        return this.vpv1;
    }
    
    public void setVpv1(Float vpv1) {
        this.vpv1 = vpv1;
    }
    
    @Column(name="vpv2", precision=12, scale=0)
    public Float getVpv2() {
        return this.vpv2;
    }
    
    public void setVpv2(Float vpv2) {
        this.vpv2 = vpv2;
    }
    
    @Column(name="vpv3", precision=12, scale=0)
    public Float getVpv3() {
        return this.vpv3;
    }
    
    public void setVpv3(Float vpv3) {
        this.vpv3 = vpv3;
    }
    
    @Column(name="lpv1", precision=12, scale=0)
    public Float getLpv1() {
        return this.lpv1;
    }
    
    public void setLpv1(Float lpv1) {
        this.lpv1 = lpv1;
    }
    
    @Column(name="lpv2", precision=12, scale=0)
    public Float getLpv2() {
        return this.lpv2;
    }
    
    public void setLpv2(Float lpv2) {
        this.lpv2 = lpv2;
    }
    
    @Column(name="lpv3", precision=12, scale=0)
    public Float getLpv3() {
        return this.lpv3;
    }
    
    public void setLpv3(Float lpv3) {
        this.lpv3 = lpv3;
    }
    
    @Column(name="vac1", precision=12, scale=0)
    public Float getVac1() {
        return this.vac1;
    }
    
    public void setVac1(Float vac1) {
        this.vac1 = vac1;
    }
    
    @Column(name="vac2", precision=12, scale=0)
    public Float getVac2() {
        return this.vac2;
    }
    
    public void setVac2(Float vac2) {
        this.vac2 = vac2;
    }
    
    @Column(name="vac3", precision=12, scale=0)
    public Float getVac3() {
        return this.vac3;
    }
    
    public void setVac3(Float vac3) {
        this.vac3 = vac3;
    }
    
    @Column(name="lac1", precision=12, scale=0)
    public Float getLac1() {
        return this.lac1;
    }
    
    public void setLac1(Float lac1) {
        this.lac1 = lac1;
    }
    
    @Column(name="lac2", precision=12, scale=0)
    public Float getLac2() {
        return this.lac2;
    }
    
    public void setLac2(Float lac2) {
        this.lac2 = lac2;
    }
    
    @Column(name="lac3", precision=12, scale=0)
    public Float getLac3() {
        return this.lac3;
    }
    
    public void setLac3(Float lac3) {
        this.lac3 = lac3;
    }
    
    @Column(name="pac1", precision=12, scale=0)
    public Float getPac1() {
        return this.pac1;
    }
    
    public void setPac1(Float pac1) {
        this.pac1 = pac1;
    }
    
    @Column(name="pac2", precision=12, scale=0)
    public Float getPac2() {
        return this.pac2;
    }
    
    public void setPac2(Float pac2) {
        this.pac2 = pac2;
    }
    
    @Column(name="pac3", precision=12, scale=0)
    public Float getPac3() {
        return this.pac3;
    }
    
    public void setPac3(Float pac3) {
        this.pac3 = pac3;
    }
    
    @Column(name="fac", precision=12, scale=0)
    public Float getFac() {
        return this.fac;
    }
    
    public void setFac(Float fac) {
        this.fac = fac;
    }
    
    @Column(name="today_ene", precision=12, scale=0)
    public Float getTodayEne() {
        return this.todayEne;
    }
    
    public void setTodayEne(Float todayEne) {
        this.todayEne = todayEne;
    }
    
    @Column(name="total_ene", precision=12, scale=0)
    public Float getTotalEne() {
        return this.totalEne;
    }
    
    public void setTotalEne(Float totalEne) {
        this.totalEne = totalEne;
    }




}


