package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Info generated by hbm2java
 */
@Entity
@Table(name = "info", catalog = "ele")
public class Info implements java.io.Serializable {

	private Long id;
	private Long idProject;
	private String code;
	private String c1;
	private String c2;
	private String c3;
	private String c4;
	private String c5;
	private String c6;
	private String c7;
	private String c8;
	private String c9;
	private String c10;
	private String c11;
	private String c12;
	private String c13;
	private String c14;
	private String c15;
	private String c16;
	private String c17;
	private String c18;
	private String c19;
	private String c20;
	private String c21;
	private String c22;
	private String c23;
	private String c24;
	private String c25;
	private String c26;
	private String c27;
	private String c28;
	private String c29;
	private String c30;
	private String c31;
	private String c32;
	private String c33;
	private String c34;
	private String c35;
	private String c36;
	private String c37;
	private String c38;
	private String c39;
	private String c40;
	private String c41;
	private String c42;
	private String c43;
	private String c44;
	private String c45;
	private String c46;
	private String c47;
	private String c48;
	private String c49;
	private String c50;
	private String c51;
	private String c52;
	private String c53;
	private String c54;
	private String c55;
	private String c56;
	private String c57;
	private String c58;
	private String c59;
	private String c60;
	private String c61;
	private String c62;
	private String c63;
	private String c64;
	private Date d1;
	private Date d2;
	private Date d3;
	private Date d4;
	private Date d5;
	private Date d6;
	private Date d7;
	private Date d8;
	private Date d9;
	private Date d10;
	private Date d11;
	private String s1;
	private String s2;
	private String s3;
	private String s4;
	private String s5;
	private String s6;
	private String s7;
	private String s8;
	private String s9;
	private String s10;
	private String s11;
	private String p1;
	private String p2;
	private String p3;
	private String p4;
	private String p5;
	private String p6;
	private String p7;
	private String p8;
	//private ProjectSteps projectSteps;
	
	private String content;

	// private Long idProject;
	@Column(name = "id_project")
	public Long getIdProject() {
		return idProject;
	}

	public void setIdProject(Long idProject) {
		this.idProject = idProject;
	}

	public Info() {
	}

	public Info(String code, String c1, String c2, String c3, String c4, String c5,
			String c6, String c7, String c8, String c9, String c10, String c11, String c12, String c13, String c14,
			String c15, String c16, String c17, String c18, String c19, String c20, String c21, String c22, String c23,
			String c24, String c25, String c26, String c27, String c28, String c29, String c30, String c31, String c32,
			String c33, String c34, String c35, String c36, String c37, String c38, String c39, String c40, String c41,
			String c42, String c43, String c44, String c45, String c46, String c47, String c48, String c49, String c50,
			String c51, String c52, String c53, String c54, String c55, String c56, String c57, String c58, String c59,
			String c60, String c61, String c62, String c63, String c64, Date d1, Date d2, Date d3, Date d4, Date d5,
			Date d6, Date d7, Date d8, Date d9, Date d10, Date d11, String s1, String s2, String s3, String s4,
			String s5, String s6, String s7, String s8, String s9, String s10, String s11, String p1, String p2,
			String p3, String p4, String p5, String p6, String p7, String p8) {
	
		this.code = code;
		this.c1 = c1;
		this.c2 = c2;
		this.c3 = c3;
		this.c4 = c4;
		this.c5 = c5;
		this.c6 = c6;
		this.c7 = c7;
		this.c8 = c8;
		this.c9 = c9;
		this.c10 = c10;
		this.c11 = c11;
		this.c12 = c12;
		this.c13 = c13;
		this.c14 = c14;
		this.c15 = c15;
		this.c16 = c16;
		this.c17 = c17;
		this.c18 = c18;
		this.c19 = c19;
		this.c20 = c20;
		this.c21 = c21;
		this.c22 = c22;
		this.c23 = c23;
		this.c24 = c24;
		this.c25 = c25;
		this.c26 = c26;
		this.c27 = c27;
		this.c28 = c28;
		this.c29 = c29;
		this.c30 = c30;
		this.c31 = c31;
		this.c32 = c32;
		this.c33 = c33;
		this.c34 = c34;
		this.c35 = c35;
		this.c36 = c36;
		this.c37 = c37;
		this.c38 = c38;
		this.c39 = c39;
		this.c40 = c40;
		this.c41 = c41;
		this.c42 = c42;
		this.c43 = c43;
		this.c44 = c44;
		this.c45 = c45;
		this.c46 = c46;
		this.c47 = c47;
		this.c48 = c48;
		this.c49 = c49;
		this.c50 = c50;
		this.c51 = c51;
		this.c52 = c52;
		this.c53 = c53;
		this.c54 = c54;
		this.c55 = c55;
		this.c56 = c56;
		this.c57 = c57;
		this.c58 = c58;
		this.c59 = c59;
		this.c60 = c60;
		this.c61 = c61;
		this.c62 = c62;
		this.c63 = c63;
		this.c64 = c64;
		this.d1 = d1;
		this.d2 = d2;
		this.d3 = d3;
		this.d4 = d4;
		this.d5 = d5;
		this.d6 = d6;
		this.d7 = d7;
		this.d8 = d8;
		this.d9 = d9;
		this.d10 = d10;
		this.d11 = d11;
		this.s1 = s1;
		this.s2 = s2;
		this.s3 = s3;
		this.s4 = s4;
		this.s5 = s5;
		this.s6 = s6;
		this.s7 = s7;
		this.s8 = s8;
		this.s9 = s9;
		this.s10 = s10;
		this.s11 = s11;
		this.p1 = p1;
		this.p2 = p2;
		this.p3 = p3;
		this.p4 = p4;
		this.p5 = p5;
		this.p6 = p6;
		this.p7 = p7;
		this.p8 = p8;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	@Column(name = "code", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "c1", length = 64)
	public String getC1() {
		return this.c1;
	}

	public void setC1(String c1) {
		this.c1 = c1;
	}

	@Column(name = "c2", length = 64)
	public String getC2() {
		return this.c2;
	}

	public void setC2(String c2) {
		this.c2 = c2;
	}

	@Column(name = "c3", length = 64)
	public String getC3() {
		return this.c3;
	}

	public void setC3(String c3) {
		this.c3 = c3;
	}

	@Column(name = "c4", length = 64)
	public String getC4() {
		return this.c4;
	}

	public void setC4(String c4) {
		this.c4 = c4;
	}

	@Column(name = "c5", length = 64)
	public String getC5() {
		return this.c5;
	}

	public void setC5(String c5) {
		this.c5 = c5;
	}

	@Column(name = "c6", length = 64)
	public String getC6() {
		return this.c6;
	}

	public void setC6(String c6) {
		this.c6 = c6;
	}

	@Column(name = "c7", length = 64)
	public String getC7() {
		return this.c7;
	}

	public void setC7(String c7) {
		this.c7 = c7;
	}

	@Column(name = "c8", length = 64)
	public String getC8() {
		return this.c8;
	}

	public void setC8(String c8) {
		this.c8 = c8;
	}

	@Column(name = "c9", length = 64)
	public String getC9() {
		return this.c9;
	}

	public void setC9(String c9) {
		this.c9 = c9;
	}

	@Column(name = "c10", length = 64)
	public String getC10() {
		return this.c10;
	}

	public void setC10(String c10) {
		this.c10 = c10;
	}

	@Column(name = "c11", length = 64)
	public String getC11() {
		return this.c11;
	}

	public void setC11(String c11) {
		this.c11 = c11;
	}

	@Column(name = "c12", length = 64)
	public String getC12() {
		return this.c12;
	}

	public void setC12(String c12) {
		this.c12 = c12;
	}

	@Column(name = "c13", length = 64)
	public String getC13() {
		return this.c13;
	}

	public void setC13(String c13) {
		this.c13 = c13;
	}

	@Column(name = "c14", length = 64)
	public String getC14() {
		return this.c14;
	}

	public void setC14(String c14) {
		this.c14 = c14;
	}

	@Column(name = "c15", length = 64)
	public String getC15() {
		return this.c15;
	}

	public void setC15(String c15) {
		this.c15 = c15;
	}

	@Column(name = "c16", length = 64)
	public String getC16() {
		return this.c16;
	}

	public void setC16(String c16) {
		this.c16 = c16;
	}

	@Column(name = "c17", length = 64)
	public String getC17() {
		return this.c17;
	}

	public void setC17(String c17) {
		this.c17 = c17;
	}

	@Column(name = "c18", length = 64)
	public String getC18() {
		return this.c18;
	}

	public void setC18(String c18) {
		this.c18 = c18;
	}

	@Column(name = "c19", length = 64)
	public String getC19() {
		return this.c19;
	}

	public void setC19(String c19) {
		this.c19 = c19;
	}

	@Column(name = "c20", length = 64)
	public String getC20() {
		return this.c20;
	}

	public void setC20(String c20) {
		this.c20 = c20;
	}

	@Column(name = "c21", length = 64)
	public String getC21() {
		return this.c21;
	}

	public void setC21(String c21) {
		this.c21 = c21;
	}

	@Column(name = "c22", length = 64)
	public String getC22() {
		return this.c22;
	}

	public void setC22(String c22) {
		this.c22 = c22;
	}

	@Column(name = "c23", length = 64)
	public String getC23() {
		return this.c23;
	}

	public void setC23(String c23) {
		this.c23 = c23;
	}

	@Column(name = "c24", length = 64)
	public String getC24() {
		return this.c24;
	}

	public void setC24(String c24) {
		this.c24 = c24;
	}

	@Column(name = "c25", length = 64)
	public String getC25() {
		return this.c25;
	}

	public void setC25(String c25) {
		this.c25 = c25;
	}

	@Column(name = "c26", length = 64)
	public String getC26() {
		return this.c26;
	}

	public void setC26(String c26) {
		this.c26 = c26;
	}

	@Column(name = "c27", length = 64)
	public String getC27() {
		return this.c27;
	}

	public void setC27(String c27) {
		this.c27 = c27;
	}

	@Column(name = "c28", length = 64)
	public String getC28() {
		return this.c28;
	}

	public void setC28(String c28) {
		this.c28 = c28;
	}

	@Column(name = "c29", length = 64)
	public String getC29() {
		return this.c29;
	}

	public void setC29(String c29) {
		this.c29 = c29;
	}

	@Column(name = "c30", length = 64)
	public String getC30() {
		return this.c30;
	}

	public void setC30(String c30) {
		this.c30 = c30;
	}

	@Column(name = "c31", length = 64)
	public String getC31() {
		return this.c31;
	}

	public void setC31(String c31) {
		this.c31 = c31;
	}

	@Column(name = "c32", length = 64)
	public String getC32() {
		return this.c32;
	}

	public void setC32(String c32) {
		this.c32 = c32;
	}

	@Column(name = "c33", length = 64)
	public String getC33() {
		return this.c33;
	}

	public void setC33(String c33) {
		this.c33 = c33;
	}

	@Column(name = "c34", length = 64)
	public String getC34() {
		return this.c34;
	}

	public void setC34(String c34) {
		this.c34 = c34;
	}

	@Column(name = "c35", length = 64)
	public String getC35() {
		return this.c35;
	}

	public void setC35(String c35) {
		this.c35 = c35;
	}

	@Column(name = "c36", length = 64)
	public String getC36() {
		return this.c36;
	}

	public void setC36(String c36) {
		this.c36 = c36;
	}

	@Column(name = "c37", length = 64)
	public String getC37() {
		return this.c37;
	}

	public void setC37(String c37) {
		this.c37 = c37;
	}

	@Column(name = "c38", length = 64)
	public String getC38() {
		return this.c38;
	}

	public void setC38(String c38) {
		this.c38 = c38;
	}

	@Column(name = "c39", length = 64)
	public String getC39() {
		return this.c39;
	}

	public void setC39(String c39) {
		this.c39 = c39;
	}

	@Column(name = "c40", length = 64)
	public String getC40() {
		return this.c40;
	}

	public void setC40(String c40) {
		this.c40 = c40;
	}

	@Column(name = "c41", length = 64)
	public String getC41() {
		return this.c41;
	}

	public void setC41(String c41) {
		this.c41 = c41;
	}

	@Column(name = "c42", length = 64)
	public String getC42() {
		return this.c42;
	}

	public void setC42(String c42) {
		this.c42 = c42;
	}

	@Column(name = "c43", length = 64)
	public String getC43() {
		return this.c43;
	}

	public void setC43(String c43) {
		this.c43 = c43;
	}

	@Column(name = "c44", length = 64)
	public String getC44() {
		return this.c44;
	}

	public void setC44(String c44) {
		this.c44 = c44;
	}

	@Column(name = "c45", length = 64)
	public String getC45() {
		return this.c45;
	}

	public void setC45(String c45) {
		this.c45 = c45;
	}

	@Column(name = "c46", length = 64)
	public String getC46() {
		return this.c46;
	}

	public void setC46(String c46) {
		this.c46 = c46;
	}

	@Column(name = "c47", length = 64)
	public String getC47() {
		return this.c47;
	}

	public void setC47(String c47) {
		this.c47 = c47;
	}

	@Column(name = "c48", length = 64)
	public String getC48() {
		return this.c48;
	}

	public void setC48(String c48) {
		this.c48 = c48;
	}

	@Column(name = "c49", length = 64)
	public String getC49() {
		return this.c49;
	}

	public void setC49(String c49) {
		this.c49 = c49;
	}

	@Column(name = "c50", length = 64)
	public String getC50() {
		return this.c50;
	}

	public void setC50(String c50) {
		this.c50 = c50;
	}

	@Column(name = "c51", length = 64)
	public String getC51() {
		return this.c51;
	}

	public void setC51(String c51) {
		this.c51 = c51;
	}

	@Column(name = "c52", length = 64)
	public String getC52() {
		return this.c52;
	}

	public void setC52(String c52) {
		this.c52 = c52;
	}

	@Column(name = "c53", length = 64)
	public String getC53() {
		return this.c53;
	}

	public void setC53(String c53) {
		this.c53 = c53;
	}

	@Column(name = "c54", length = 64)
	public String getC54() {
		return this.c54;
	}

	public void setC54(String c54) {
		this.c54 = c54;
	}

	@Column(name = "c55", length = 64)
	public String getC55() {
		return this.c55;
	}

	public void setC55(String c55) {
		this.c55 = c55;
	}

	@Column(name = "c56", length = 64)
	public String getC56() {
		return this.c56;
	}

	public void setC56(String c56) {
		this.c56 = c56;
	}

	@Column(name = "c57", length = 64)
	public String getC57() {
		return this.c57;
	}

	public void setC57(String c57) {
		this.c57 = c57;
	}

	@Column(name = "c58", length = 64)
	public String getC58() {
		return this.c58;
	}

	public void setC58(String c58) {
		this.c58 = c58;
	}

	@Column(name = "c59", length = 64)
	public String getC59() {
		return this.c59;
	}

	public void setC59(String c59) {
		this.c59 = c59;
	}

	@Column(name = "c60", length = 64)
	public String getC60() {
		return this.c60;
	}

	public void setC60(String c60) {
		this.c60 = c60;
	}

	@Column(name = "c61", length = 64)
	public String getC61() {
		return this.c61;
	}

	public void setC61(String c61) {
		this.c61 = c61;
	}

	@Column(name = "c62", length = 64)
	public String getC62() {
		return this.c62;
	}

	public void setC62(String c62) {
		this.c62 = c62;
	}

	@Column(name = "c63", length = 64)
	public String getC63() {
		return this.c63;
	}

	public void setC63(String c63) {
		this.c63 = c63;
	}

	@Column(name = "c64", length = 64)
	public String getC64() {
		return this.c64;
	}

	public void setC64(String c64) {
		this.c64 = c64;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d1", length = 19)
	public Date getD1() {
		return this.d1;
	}

	public void setD1(Date d1) {
		this.d1 = d1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d2", length = 19)
	public Date getD2() {
		return this.d2;
	}

	public void setD2(Date d2) {
		this.d2 = d2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d3", length = 19)
	public Date getD3() {
		return this.d3;
	}

	public void setD3(Date d3) {
		this.d3 = d3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d4", length = 19)
	public Date getD4() {
		return this.d4;
	}

	public void setD4(Date d4) {
		this.d4 = d4;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d5", length = 19)
	public Date getD5() {
		return this.d5;
	}

	public void setD5(Date d5) {
		this.d5 = d5;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d6", length = 19)
	public Date getD6() {
		return this.d6;
	}

	public void setD6(Date d6) {
		this.d6 = d6;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d7", length = 19)
	public Date getD7() {
		return this.d7;
	}

	public void setD7(Date d7) {
		this.d7 = d7;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d8", length = 19)
	public Date getD8() {
		return this.d8;
	}

	public void setD8(Date d8) {
		this.d8 = d8;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d9", length = 19)
	public Date getD9() {
		return this.d9;
	}

	public void setD9(Date d9) {
		this.d9 = d9;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d10", length = 19)
	public Date getD10() {
		return this.d10;
	}

	public void setD10(Date d10) {
		this.d10 = d10;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "d11", length = 19)
	public Date getD11() {
		return this.d11;
	}

	public void setD11(Date d11) {
		this.d11 = d11;
	}

	@Column(name = "s1", length = 64)
	public String getS1() {
		return this.s1;
	}

	public void setS1(String s1) {
		this.s1 = s1;
	}

	@Column(name = "s2", length = 64)
	public String getS2() {
		return this.s2;
	}

	public void setS2(String s2) {
		this.s2 = s2;
	}

	@Column(name = "s3", length = 64)
	public String getS3() {
		return this.s3;
	}

	public void setS3(String s3) {
		this.s3 = s3;
	}

	@Column(name = "s4", length = 64)
	public String getS4() {
		return this.s4;
	}

	public void setS4(String s4) {
		this.s4 = s4;
	}

	@Column(name = "s5", length = 64)
	public String getS5() {
		return this.s5;
	}

	public void setS5(String s5) {
		this.s5 = s5;
	}

	@Column(name = "s6", length = 64)
	public String getS6() {
		return this.s6;
	}

	public void setS6(String s6) {
		this.s6 = s6;
	}

	@Column(name = "s7", length = 64)
	public String getS7() {
		return this.s7;
	}

	public void setS7(String s7) {
		this.s7 = s7;
	}

	@Column(name = "s8", length = 64)
	public String getS8() {
		return this.s8;
	}

	public void setS8(String s8) {
		this.s8 = s8;
	}

	@Column(name = "s9", length = 64)
	public String getS9() {
		return this.s9;
	}

	public void setS9(String s9) {
		this.s9 = s9;
	}

	@Column(name = "s10", length = 64)
	public String getS10() {
		return this.s10;
	}

	public void setS10(String s10) {
		this.s10 = s10;
	}

	@Column(name = "s11", length = 64)
	public String getS11() {
		return this.s11;
	}

	public void setS11(String s11) {
		this.s11 = s11;
	}

	@Column(name = "p1", length = 128)
	public String getP1() {
		return this.p1;
	}

	public void setP1(String p1) {
		this.p1 = p1;
	}

	@Column(name = "p2", length = 128)
	public String getP2() {
		return this.p2;
	}

	public void setP2(String p2) {
		this.p2 = p2;
	}

	@Column(name = "p3", length = 128)
	public String getP3() {
		return this.p3;
	}

	public void setP3(String p3) {
		this.p3 = p3;
	}

	@Column(name = "p4", length = 128)
	public String getP4() {
		return this.p4;
	}

	public void setP4(String p4) {
		this.p4 = p4;
	}

	@Column(name = "p5", length = 128)
	public String getP5() {
		return this.p5;
	}

	public void setP5(String p5) {
		this.p5 = p5;
	}

	@Column(name = "p6", length = 128)
	public String getP6() {
		return this.p6;
	}

	public void setP6(String p6) {
		this.p6 = p6;
	}

	@Column(name = "p7", length = 128)
	public String getP7() {
		return this.p7;
	}

	public void setP7(String p7) {
		this.p7 = p7;
	}

	@Column(name = "p8", length = 128)
	public String getP8() {
		return this.p8;
	}

	public void setP8(String p8) {
		this.p8 = p8;
	}

	//@Lob(type = LobType.CLOB, fetch = FetchType.LAZY)  
	@Column(name="content",length = 16777216)
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}
	


}
