package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Loan generated by hbm2java
 */
@Entity
@Table(name="loan"
    ,catalog="ele"
)
public class Loan  implements java.io.Serializable {


     private Long id;
     private ProjectSteps projectSteps;
     private Customer customer;
     private String code;
     private String bank;
     private Long duration;
     private Long capacity;
     private Long radio;
     private Long amount;
     private Float amountPermonth;
     private String paymentTime;
     private Float unitPrice;
     private Float subsidyPrice;
     private Float estimateCapacity;
     private Float estimateIncomePermonth;
     private Float estimateIncomePeryear;
     private Float actCapacity;
     private Float actIncomePermonth;
     private Float actIncomePeryear;
     private Float recharge;
     private Float balance;
     private Float risk;

    public Loan() {
    }

    public Loan(ProjectSteps projectSteps, Customer customer, String code, String bank, Long duration, Long capacity, Long radio, Long amount, Float amountPermonth, String paymentTime, Float unitPrice, Float subsidyPrice, Float estimateCapacity, Float estimateIncomePermonth, Float estimateIncomePeryear, Float actCapacity, Float actIncomePermonth, Float actIncomePeryear, Float recharge, Float balance, Float risk) {
       this.projectSteps = projectSteps;
       this.customer = customer;
       this.code = code;
       this.bank = bank;
       this.duration = duration;
       this.capacity = capacity;
       this.radio = radio;
       this.amount = amount;
       this.amountPermonth = amountPermonth;
       this.paymentTime = paymentTime;
       this.unitPrice = unitPrice;
       this.subsidyPrice = subsidyPrice;
       this.estimateCapacity = estimateCapacity;
       this.estimateIncomePermonth = estimateIncomePermonth;
       this.estimateIncomePeryear = estimateIncomePeryear;
       this.actCapacity = actCapacity;
       this.actIncomePermonth = actIncomePermonth;
       this.actIncomePeryear = actIncomePeryear;
       this.recharge = recharge;
       this.balance = balance;
       this.risk = risk;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_project_step")
    public ProjectSteps getProjectSteps() {
        return this.projectSteps;
    }
    
    public void setProjectSteps(ProjectSteps projectSteps) {
        this.projectSteps = projectSteps;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_customer")
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    
    @Column(name="code", length=64)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="bank", length=64)
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }
    
    @Column(name="duration")
    public Long getDuration() {
        return this.duration;
    }
    
    public void setDuration(Long duration) {
        this.duration = duration;
    }
    
    @Column(name="capacity")
    public Long getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Long capacity) {
        this.capacity = capacity;
    }
    
    @Column(name="radio")
    public Long getRadio() {
        return this.radio;
    }
    
    public void setRadio(Long radio) {
        this.radio = radio;
    }
    
    @Column(name="amount")
    public Long getAmount() {
        return this.amount;
    }
    
    public void setAmount(Long amount) {
        this.amount = amount;
    }
    
    @Column(name="amount_permonth", precision=12, scale=0)
    public Float getAmountPermonth() {
        return this.amountPermonth;
    }
    
    public void setAmountPermonth(Float amountPermonth) {
        this.amountPermonth = amountPermonth;
    }
    
    @Column(name="payment_time", length=20)
    public String getPaymentTime() {
        return this.paymentTime;
    }
    
    public void setPaymentTime(String paymentTime) {
        this.paymentTime = paymentTime;
    }
    
    @Column(name="unit_price", precision=12, scale=0)
    public Float getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Float unitPrice) {
        this.unitPrice = unitPrice;
    }
    
    @Column(name="subsidy_price", precision=12, scale=0)
    public Float getSubsidyPrice() {
        return this.subsidyPrice;
    }
    
    public void setSubsidyPrice(Float subsidyPrice) {
        this.subsidyPrice = subsidyPrice;
    }
    
    @Column(name="estimate_capacity", precision=12, scale=0)
    public Float getEstimateCapacity() {
        return this.estimateCapacity;
    }
    
    public void setEstimateCapacity(Float estimateCapacity) {
        this.estimateCapacity = estimateCapacity;
    }
    
    @Column(name="estimate_income_permonth", precision=12, scale=0)
    public Float getEstimateIncomePermonth() {
        return this.estimateIncomePermonth;
    }
    
    public void setEstimateIncomePermonth(Float estimateIncomePermonth) {
        this.estimateIncomePermonth = estimateIncomePermonth;
    }
    
    @Column(name="estimate_income_peryear", precision=12, scale=0)
    public Float getEstimateIncomePeryear() {
        return this.estimateIncomePeryear;
    }
    
    public void setEstimateIncomePeryear(Float estimateIncomePeryear) {
        this.estimateIncomePeryear = estimateIncomePeryear;
    }
    
    @Column(name="act_capacity", precision=12, scale=0)
    public Float getActCapacity() {
        return this.actCapacity;
    }
    
    public void setActCapacity(Float actCapacity) {
        this.actCapacity = actCapacity;
    }
    
    @Column(name="act_income_permonth", precision=12, scale=0)
    public Float getActIncomePermonth() {
        return this.actIncomePermonth;
    }
    
    public void setActIncomePermonth(Float actIncomePermonth) {
        this.actIncomePermonth = actIncomePermonth;
    }
    
    @Column(name="act_income_peryear", precision=12, scale=0)
    public Float getActIncomePeryear() {
        return this.actIncomePeryear;
    }
    
    public void setActIncomePeryear(Float actIncomePeryear) {
        this.actIncomePeryear = actIncomePeryear;
    }
    
    @Column(name="recharge", precision=12, scale=0)
    public Float getRecharge() {
        return this.recharge;
    }
    
    public void setRecharge(Float recharge) {
        this.recharge = recharge;
    }
    
    @Column(name="balance", precision=12, scale=0)
    public Float getBalance() {
        return this.balance;
    }
    
    public void setBalance(Float balance) {
        this.balance = balance;
    }
    
    @Column(name="risk", precision=12, scale=0)
    public Float getRisk() {
        return this.risk;
    }
    
    public void setRisk(Float risk) {
        this.risk = risk;
    }




}


