package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="location"
    ,catalog="ele"
)
public class Location  implements java.io.Serializable {


     private Long id;
     private SubLocation subLocation;
     private String name;

    public Location() {
    }

	
    public Location(Long id) {
        this.id = id;
    }
    public Location(Long id, SubLocation subLocation, String name) {
       this.id = id;
       this.subLocation = subLocation;
       this.name = name;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sub_loc")
    public SubLocation getSubLocation() {
        return this.subLocation;
    }
    
    public void setSubLocation(SubLocation subLocation) {
        this.subLocation = subLocation;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


