package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectSteps generated by hbm2java
 */
@Entity
@Table(name="project_steps"
    ,catalog="ele"
)
public class ProjectSteps  implements java.io.Serializable {


     private Long id;
     private Dic dicByProgress;
     private Users users;
     private Dic dicByDepartment;
     private Dic dicByStatus;
     private Steps steps;
     private Customer customer;
     private String name;
     private Long forcastDays;
     private Long lastedDays;
     private Date start;
     private Date end;
     private Long actDays;
     private String remark;
     private Set<Loan> loans = new HashSet<Loan>(0);
     private Set<Info> infos = new HashSet<Info>(0);

    public ProjectSteps() {
    }

	
    public ProjectSteps(Long id) {
        this.id = id;
    }
    public ProjectSteps(Long id, Dic dicByProgress, Users users, Dic dicByDepartment, Dic dicByStatus, Steps steps, Customer customer, String name, Long forcastDays, Long lastedDays, Date start, Date end, Long actDays, String remark, Set<Loan> loans, Set<Info> infos) {
       this.id = id;
       this.dicByProgress = dicByProgress;
       this.users = users;
       this.dicByDepartment = dicByDepartment;
       this.dicByStatus = dicByStatus;
       this.steps = steps;
       this.customer = customer;
       this.name = name;
       this.forcastDays = forcastDays;
       this.lastedDays = lastedDays;
       this.start = start;
       this.end = end;
       this.actDays = actDays;
       this.remark = remark;
       this.loans = loans;
       this.infos = infos;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="progress")
    public Dic getDicByProgress() {
        return this.dicByProgress;
    }
    
    public void setDicByProgress(Dic dicByProgress) {
        this.dicByProgress = dicByProgress;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department")
    public Dic getDicByDepartment() {
        return this.dicByDepartment;
    }
    
    public void setDicByDepartment(Dic dicByDepartment) {
        this.dicByDepartment = dicByDepartment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public Dic getDicByStatus() {
        return this.dicByStatus;
    }
    
    public void setDicByStatus(Dic dicByStatus) {
        this.dicByStatus = dicByStatus;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_step")
    public Steps getSteps() {
        return this.steps;
    }
    
    public void setSteps(Steps steps) {
        this.steps = steps;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_customer")
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="forcast_days")
    public Long getForcastDays() {
        return this.forcastDays;
    }
    
    public void setForcastDays(Long forcastDays) {
        this.forcastDays = forcastDays;
    }
    
    @Column(name="lasted_days")
    public Long getLastedDays() {
        return this.lastedDays;
    }
    
    public void setLastedDays(Long lastedDays) {
        this.lastedDays = lastedDays;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start", length=19)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end", length=19)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    
    @Column(name="act_days")
    public Long getActDays() {
        return this.actDays;
    }
    
    public void setActDays(Long actDays) {
        this.actDays = actDays;
    }
    
    @Column(name="remark", length=128)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="projectSteps")
    public Set<Loan> getLoans() {
        return this.loans;
    }
    
    public void setLoans(Set<Loan> loans) {
        this.loans = loans;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="projectSteps")
    public Set<Info> getInfos() {
        return this.infos;
    }
    
    public void setInfos(Set<Info> infos) {
        this.infos = infos;
    }




}


