package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolePages generated by hbm2java
 */
@Entity
@Table(name="role_pages"
    ,catalog="ele"
)
public class RolePages  implements java.io.Serializable {


     private RolePagesId id;
     private Dic dic;
     private Pages pages;
     private Long seq;

    public RolePages() {
    }

	
    public RolePages(RolePagesId id, Dic dic, Pages pages) {
        this.id = id;
        this.dic = dic;
        this.pages = pages;
    }
    public RolePages(RolePagesId id, Dic dic, Pages pages, Long seq) {
       this.id = id;
       this.dic = dic;
       this.pages = pages;
       this.seq = seq;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idRole", column=@Column(name="id_role", nullable=false) ), 
        @AttributeOverride(name="idPage", column=@Column(name="id_page", nullable=false) ) } )
    public RolePagesId getId() {
        return this.id;
    }
    
    public void setId(RolePagesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_role", nullable=false, insertable=false, updatable=false)
    public Dic getDic() {
        return this.dic;
    }
    
    public void setDic(Dic dic) {
        this.dic = dic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_page", nullable=false, insertable=false, updatable=false)
    public Pages getPages() {
        return this.pages;
    }
    
    public void setPages(Pages pages) {
        this.pages = pages;
    }
    
    @Column(name="seq")
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }




}


