package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Steps generated by hbm2java
 */
@Entity
@Table(name="steps"
    ,catalog="ele"
)
public class Steps  implements java.io.Serializable {


     private Long id;
     private Dic dic;
     private String name;
     private Long seq;
     private Long forcastDays;
     private Long lastedDays;
     private String form;
     private Set<Noti> notis = new HashSet<Noti>(0);
     private Set<ProjectSteps> projectStepses = new HashSet<ProjectSteps>(0);

    public Steps() {
    }

	
    public Steps(Long id) {
        this.id = id;
    }
    public Steps(Long id, Dic dic, String name, Long seq, Long forcastDays, Long lastedDays, String form, Set<Noti> notis, Set<ProjectSteps> projectStepses) {
       this.id = id;
       this.dic = dic;
       this.name = name;
       this.seq = seq;
       this.forcastDays = forcastDays;
       this.lastedDays = lastedDays;
       this.form = form;
       this.notis = notis;
       this.projectStepses = projectStepses;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department")
    public Dic getDic() {
        return this.dic;
    }
    
    public void setDic(Dic dic) {
        this.dic = dic;
    }
    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="seq")
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }
    
    @Column(name="forcast_days")
    public Long getForcastDays() {
        return this.forcastDays;
    }
    
    public void setForcastDays(Long forcastDays) {
        this.forcastDays = forcastDays;
    }
    
    @Column(name="lasted_days")
    public Long getLastedDays() {
        return this.lastedDays;
    }
    
    public void setLastedDays(Long lastedDays) {
        this.lastedDays = lastedDays;
    }
    
    @Column(name="form", length=64)
    public String getForm() {
        return this.form;
    }
    
    public void setForm(String form) {
        this.form = form;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="steps")
    public Set<Noti> getNotis() {
        return this.notis;
    }
    
    public void setNotis(Set<Noti> notis) {
        this.notis = notis;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="steps")
    public Set<ProjectSteps> getProjectStepses() {
        return this.projectStepses;
    }
    
    public void setProjectStepses(Set<ProjectSteps> projectStepses) {
        this.projectStepses = projectStepses;
    }




}


