package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;
import java.util.Date;
import javax.persistence.*;

/**
 * TransferSheet generated by hbm2java
 */

@Entity
@Table(name = "transfer_sheet", catalog = "ele")
public class TransferSheet implements java.io.Serializable {

	private Long id;
	private String code;
	private Long idProjectStep;


	private String content;
	private Long idProject;
	
	private Long commit;

	private Float actVol;

	private String projectName;

	private String address;

	@Column(name = "id_project")
	public Long getIdProject() {
		return idProject;
	}

	public void setIdProject(Long idProject) {
		this.idProject = idProject;
	}

	public TransferSheet() {
	}

	public TransferSheet(Long id) {
		this.id = id;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "code", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "id_project_step")
	public Long getIdProjectStep() {
		return this.idProjectStep;
	}

	public void setIdProjectStep(Long idProjectStep) {
		this.idProjectStep = idProjectStep;
	}


	@Column(name = "content", length = 16777216)
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "commit")
	public Long getCommit() {
		return commit;
	}

	public void setCommit(Long commit) {
		this.commit = commit;
	}

	@Column(name = "act_vol",precision = 12,scale = 0)
	public Float getActVol() {
		return actVol;
	}

	public void setActVol(Float actVol) {
		this.actVol = actVol;
	}

	@Transient
	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Transient
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
}
